name: DoorLock
version: '${project.version}'
main: com.github.e2318501.doorlock.DoorLock
api-version: '1.19'
commands:
  doorlock:
    permission: doorlock.command.doorlock
    usage: |
      /<command> create <keyType> <customModelData>
      /<command> delete
      /<command> cancel
permissions:
  doorlock.command.doorlock:
    default: op
